
CREATE TABLE [dbo].[ITEM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](40) NOT NULL,
	[DATA_CADASTRO] [datetime] NOT NULL,
	[CATEGORIA_ID] [int] NOT NULL,
	[DATA_ALTERACAO] [datetime] NULL,
 CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ITEM]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_CATEGORIA] FOREIGN KEY([CATEGORIA_ID])
REFERENCES [dbo].[CATEGORIA] ([ID])
GO

ALTER TABLE [dbo].[ITEM] CHECK CONSTRAINT [FK_ITEM_CATEGORIA]
GO


