CREATE PROCEDURE SP_S_ITEM_BUSCAR_TODOS
AS
BEGIN
	SELECT 
		CAT.ID					AS Id,
		CAT.NOME				AS 'Name',
		ITE.ID					AS Id,
		ITE.NOME				AS 'Name',
		ITE.DATA_ALTERACAO		AS DateAlter,
		ITE.DATA_CADASTRO		AS DateCreate
	

	FROM
		CATEGORIA	AS CAT
	INNER JOIN
		ITEM		AS ITE
	ON
		CAT.ID = ITE.CATEGORIA_ID
END