CREATE PROCEDURE SP_S_BUSCAR_ITEM_POR_TODOS_CAMPOS
(
	@NOME_ITEM			VARCHAR(40),  
	@CATEGORIA_ID		INT,
	@CATEGORIA_NOME		VARCHAR(20),
	@DATA_CADASTRO_ITEM	DATETIME
)
AS
BEGIN
	DECLARE @SQL VARCHAR(2000)
	DECLARE @TEM_WHERE CHAR(1)

	SET @TEM_WHERE = 'N'

	SET @SQL = N'
				SELECT
					*
				FROM
					CATEGORIA	
				INNER JOIN
					ITEM			
				ON
					CATEGORIA.ID = ITEM.CATEGORIA_ID 
		'

	IF @CATEGORIA_ID <> 0 AND @CATEGORIA_ID IS NOT NULL
	BEGIN
		SET @SQL += ' WHERE CATEGORIA.ID = '+@CATEGORIA_ID+''
		SET @TEM_WHERE = 'S'
	END

		
	IF @CATEGORIA_NOME <> '' AND @CATEGORIA_NOME IS NOT NULL
	BEGIN		
		IF @TEM_WHERE = 'N'
		BEGIN
			SET @SQL += ' WHERE CATEGORIA.NOME LIKE ''%'+@CATEGORIA_NOME+'%'''
			SET @TEM_WHERE = 'S'
		END	
		ELSE
		BEGIN
			SET @SQL += ' AND CATEGORIA.NOME LIKE ''%'+@CATEGORIA_NOME+'%'''
		END				
	END

	IF @NOME_ITEM <> '' AND @NOME_ITEM IS NOT NULL
	BEGIN
		IF @TEM_WHERE = 'N'
		BEGIN
			SET @SQL += ' WHERE ITEM.NOME LIKE ''%'+@NOME_ITEM+'%'''
			SET @TEM_WHERE = 'S'
		END	
		ELSE
		BEGIN
			SET @SQL += ' ITEM.NOME LIKE ''%'+@NOME_ITEM+'%'''
		END
	END

	IF @DATA_CADASTRO_ITEM IS NOT NULL
	BEGIN
		IF @TEM_WHERE = 'N'
		BEGIN
			SET @SQL += ' WHERE ITEM.DATA_CADASTRO = '+@DATA_CADASTRO_ITEM+''
		END
		ELSE
		BEGIN
			SET @SQL += ' AND ITEM.DATA_CADASTRO = '+@DATA_CADASTRO_ITEM+''
		END
	END	

	EXEC sp_executesql @SQL
	
END